application: rhok-keyfund
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets/js
  static_dir: assets/js
  
- url: /assets/stylesheets
  static_dir: assets/stylesheets

- url: /css
  static_dir: css

- url: /js
  static_dir: js
  
- url: /scr
  static_dir: scr

- url: /doc
  static_dir: doc
  
- url: /.*
  script: main.app

  
libraries:
- name: jinja2
  version: latest